### ISSUE TITLE
Dependencies of vpm

### ISSUE THREAD

**Issue by 0xbadshah** [libeclipse/visionary#37]
When I run `vpm` on Ubuntu 16.04 with Python version 2.7.12 , I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/vpm", line 9, in <module>
    load_entry_point('visionarypm==6.0.2', 'console_scripts', 'vpm')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/visionarypm-6.0.2-py2.7.egg/visionarypm/__init__.py", line 9, in <module>
    import scrypt
  File "build/bdist.linux-x86_64/egg/scrypt.py", line 11, in <module>
ImportError: No module named _scrypt
```

I have also tried `sudo pip install scrypt`, but theres no use.
So I think a `requirement.txt` file is required which contains the dependencies of the program.

**Comment by awnumar** [comment]
Try uninstalling both visionarypm and scrypt, then installing visionarypm.

**Comment by Chan9390** [comment]
Didn't work

**Comment by 0xbadshah** [comment]
It now works great with python2, but have some errors with python3.

**Comment by awnumar** [comment]
It should only be installed for one of the versions, since they share the vpm file that launches the program.

**Comment by awnumar** [comment]
Is this issue resolved?

**Comment by 0xbadshah** [comment]
I tried installing both separately. In python3 it showed some errors, so I uninstalled it. Whereas installation in Python2 went well.
The issue is resolved.

**Comment by awnumar** [comment]
Great. :]
